### ISSUE TITLE
Can I use that without storyboard ?

### ISSUE THREAD

**Issue by mertkanchelik** [tryWabbit/Layout-Helper#1]
Hi im trying to develop app without storyboard and I couldn't figure out how to change constraints for each device size. I was using LayoutHelper on storyboard but now as I said im trying to develop without storyboard so is it possible to do it with code

**Comment by tryWabbit** [comment]
**Absolutely Yes!**

Just copy the `DeviceHelper.swift` Into your project or the all the files of Layout Helper directory if you want to use other Features and follow these steps :- 

• Create an IBOutlet of your constraint like 

`@IBOutlet weak var constraintButtonHeight: NSLayoutConstraint!`

• In you view did load or anywhere where you want to check and update your constraint 

```
switch UIDevice().type {
    case . iPhone6:
        constraintButtonHeight.constant = 40.0
        break
    case . iPhone6plus:
        constraintButtonHeight.constant = 44.0
        break
    default:
        break
}
```
See the `Model` enum in `DeviceHelper.swift ` for more devices. Let me know if this solve your problem.

**Comment by mertkanchelik** [comment]
thank you so much for your reply but I don't know how to assign that constraint to button :( im new in programming

**Comment by tryWabbit** [comment]
No problem at all!
If you adding everything programatically you must assigning constraint this way to your UI elements, Suppose you have a UIButton 

`let button = UIButton()
`

create a global constraint in your view controller like

`var height : NSLayoutConstraint!`

in your viewDidLoad and anywhere you want to assign or update the constraint just do : - 

`height = NSLayoutConstraint(item: button, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .height, multiplier: 1.0, constant: 40)`

And update the constraint according to your need : -

```
switch UIDevice().type {
    case . iPhone6:
        height.constant = 40.0
        break
    case . iPhone6plus:
        height.constant = 44.0
        break
    default:
        break
}
```
