### ISSUE TITLE
Are iPhone 12 screens supported?

### ISSUE THREAD

**Issue by vkhadyka** [tryWabbit/Layout-Helper#12]
Any changes to update library for iPhone 12 screen support?

**Comment by joaobose** [comment]
I have the same question

**Comment by punitsilversky** [comment]
Hi @tryWabbit,

**Comment by punitsilversky** [comment]
Hi @tryWabbit,

**Comment by punitsilversky** [comment]
Hi @tryWabbit,

Please Add Support for new iPhone & iPad Devices.

Thanks!

**Comment by tryWabbit** [comment]
@vkhadyka @joaobose @punitsilversky 
Hey guys! 

I'm sorry I wasn't active here for a while. 

I've updated the library to support the latest iPhones. Soon will be updating it for iPad too. Let me know if you face any issues.

v1.0.0 has updated devices. Feel free to open this issue again if you face any problem
