### ISSUE TITLE
It doesn't update Storyboard in Xcode 12.3

### ISSUE THREAD

**Issue by elanovasconcelos** [tryWabbit/Layout-Helper#15]
The LayoutHelper is working, but the changes doesn't appear in a Storyboard after select a different device. I added changes for iPhone SE and iPhone 8 Plus for example

**Comment by tryWabbit** [comment]
Thanks for informing @elanovasconcelos .  Can you share more info for me to debug?

**Comment by tryWabbit** [comment]
Closing the issue due to no response.
