### ISSUE TITLE
No change on iphone 12 constraint

### ISSUE THREAD

**Issue by cemardaergezer** [tryWabbit/Layout-Helper#17]
I set the constraint differently for all devices and they all worked fine, but whatever I do, the Label's constraint for iPhone 12 appears in the same place. Please help.

**Comment by tryWabbit** [comment]
Can you please help me out with more detail? I just have tested and it's working fine. maybe you're missing something?

**Comment by tryWabbit** [comment]
Closing the issue because of no response.
