### ISSUE TITLE
Seems to not be working for me

### ISSUE THREAD

**Issue by tsquared11** [tryWabbit/Layout-Helper#3]
There are a bunch of alerts in the console:

"Unknown class NSLayoutHelper in Interface Builder file."

"Failed to set (iPhoneXR) user defined inspected property on (NSLayoutConstraint): [<NSLayoutConstraint 0x600002e781e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key iPhoneXR."  (this one is repeated for all of the different device types)
<img width="1280" alt="Screen Shot 2019-09-29 at 2 49 00 PM" src="https://user-images.githubusercontent.com/54460415/65838687-bc801c00-e2d3-11e9-92e9-d56ae900b048.png">
<img width="743" alt="Screen Shot 2019-09-29 at 4 06 58 PM" src="https://user-images.githubusercontent.com/54460415/65838688-bc801c00-e2d3-11e9-9a50-cb733c4fb542.png">

**Comment by tryWabbit** [comment]
Hi @tsquared11 
Can you tell me the steps for how you added layout helper in your project? Seems like it is not imported in your project.

**Comment by tsquared11** [comment]
Yes, thanks for getting back to me, it does seem like that is likely the issue from looking around, sorry I'm new to this, I downloaded the zip and then dragged it into the project.

**Comment by tryWabbit** [comment]
No problem, thanks for using my library. I just tested and it's working fine. can you share your code if it's not private or some kind of remote access, would love to help you out.

**Comment by tsquared11** [comment]
Maybe a zoom call and I can share my screen? Thanks!

**Comment by tryWabbit** [comment]
Sure, try to schedule a meeting with kuldeeptanwar1007@gmail.com .

**Comment by tsquared11** [comment]
Ok, will do, thanks!

**Comment by tryWabbit** [comment]
Issue was resolved, there was an problem in importing the files. Cheers!
