### ISSUE TITLE
What happens when a new device with new screen size comes out?

### ISSUE THREAD

**Issue by mehmetdelikaya** [tryWabbit/Layout-Helper#4]
Do you think your library handles it or we need to add the new case?

**Comment by tryWabbit** [comment]
Good question!
As the new devices come, we need to update the library like any other library. it'll depend on the screen size. if it's the same size it'll work like usual but when a new screen size will be introduced we have to update our library. 
I'll look forward to that.
Thanks @mehmetdelikaya

**Comment by mdtipusultan** [comment]
how can we add 13 devices in your library. or will you update this?

**Comment by DmiKuklin-front** [comment]
Why don't you support iPhone8, it's most problem case
