### ISSUE TITLE
pod spec is incorrect

### ISSUE THREAD

**Issue by greggjaskiewicz** [tryWabbit/Layout-Helper#5]
[!] Error installing LayoutHelper
[!] /usr/bin/git clone https://github.com/tryWabbit/Layout-Helper-Pod.git /var/folders/mw/ysbh486s65sdkdr7xyw_ckdh0000gn/T/d20200303-98246-1nihzqm --template= --single-branch --depth 1 --branch 0.1.2

**Comment by tryWabbit** [comment]
I've resolved the issue, you can find the updated code in the latest version.

**Comment by jumbochicken** [comment]
The same issue happens again.
Please help!
thanks.
