### ISSUE TITLE
iPhoneSE2 missing

### ISSUE THREAD

**Issue by andrelabbe** [tryWabbit/Layout-Helper#7]
Hi
would it be possible to update for the iPhone SE2 please. I know it is as a iPhone8
the site where you got the info  'files' has updated its info
https://stackoverflow.com/questions/26028918/how-to-determine-the-current-iphone-device-model/46234519#46234519.
there are quite few others too....
No big deal but it would be nice.

Anyway  Great job and it does the trick

regards,
andre

**Comment by RankoR** [comment]
You can just use iPhone 8, it has the same screen parameters.

**Comment by grayfeather313** [comment]
Are there still plans on keeping this up to date?

Thanks!

**Comment by tryWabbit** [comment]
@andrelabbe @zeitoun26  Thank you for your patience guys. I've updated the library. v1.0.0. Feel free to open this threat if you face any issue
